{% set version = "2.9.3" %}

package:
    name: libxml2
    version: {{ version }}

source:
    fn: libxml2-{{ version }}.tar.gz
    url: ftp://xmlsoft.org/libxml2/libxml2-{{ version }}.tar.gz
    sha256: 4de9e31f46b44d34871c22f54bfc54398ef124d6f7cafb1f4a5958fbcd3ba12d

build:
    number: 5
    features:
        - vc9     # [win and py27]
        - vc10    # [win and py34]
        - vc14    # [win and py35]

requirements:
    build:
        - python  # [win]
        - autoconf  # [not win]
        - automake  # [not win]
        - libtool  # [not win]
        - pkg-config  # [not win]
        - icu  # [not win]
        - libiconv  # [not win]
        - zlib
        - xz 5.0.*  # [not win]
    run:
        - icu  # [not win]
        - libiconv  # [not win]
        - zlib
        - xz 5.0.*  # [not win]

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    files:
        - test.xml
    commands:
        - xmllint test.xml

about:
    home: http://xmlsoft.org/
    license: MIT
    summary: The XML C parser and toolkit of Gnome

extra:
    recipe-maintainers:
        - ocefpaf
        - jakirkham
        - msarahan
