{% set version = "2.9.3" %}

package:
    name: libxml2
    version: {{ version }}

source:
    fn: libxml2-{{ version }}.tar.gz
    url: https://git.gnome.org/browse/libxml2/snapshot/libxml2-{{ version }}.tar.gz
    sha256: 473e8a80775f796a6ae8e44138a14081d21a93b38251af76e5a149afb94e980d

build:
    number: 10
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - autoconf  # [not win]
        - automake  # [not win]
        - libtool  # [not win]
        - pkg-config  # [not win]
        - icu 56.*  # [not win]
        - libiconv
        - zlib 1.2.*
    run:
        - icu 56.*  # [not win]
        - libiconv
        - zlib 1.2.*

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    files:
        - test.xml
    commands:
        - xmllint test.xml
        - conda inspect linkages -n _test libxml2  # [not win]

about:
    home: http://xmlsoft.org/
    license: MIT
    summary: 'The XML C parser and toolkit of Gnome.'

extra:
    recipe-maintainers:
        - ocefpaf
        - jakirkham
        - gillins
