{% set version = "2.9.3" %}

package:
    name: libxml2
    version: {{ version }}

source:
    fn: libxml2-{{ version }}.tar.xz
    url: https://git.gnome.org/browse/libxml2/snapshot/libxml2-{{ version }}.tar.xz
    md5: 59d281614c87d0c767134c55de20a8a9

build:
    number: 7
    skip: True  # [win]

requirements:
    build:
        - autoconf
        - automake
        - libtool
        - pkg-config
        - icu 56.* 56.*
        - libiconv
        - zlib 1.2.*
        - xz 5.0.*  # [not win]
    run:
        - icu 56.*
        - libiconv
        - zlib 1.2.*
        - xz 5.0.*  # [not win]

test:
    files:
        - test.xml
    commands:
        - xmllint test.xml
        - conda inspect linkages -n _test libxml2  # [linux]

about:
    home: http://xmlsoft.org/
    license: MIT
    summary: The XML C parser and toolkit of Gnome

extra:
    recipe-maintainers:
        - ocefpaf
        - jakirkham
