{% set version = "2.9.4" %}

package:
    name: libxml2
    version: {{ version }}

source:
    fn: libxml2-{{ version }}.tar.gz
    url: https://git.gnome.org/browse/libxml2/snapshot/libxml2-{{ version }}.tar.gz
    sha256: 1d5257abac02aab323bf6ab26199ce0bb2a7b798bb7acea302e136438237268a

build:
    number: 0
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - autoconf  # [not win]
        - automake  # [not win]
        - libtool  # [not win]
        - pkg-config  # [not win]
        - icu 56.*  # [not win]
        - libiconv
        - zlib 1.2.*
        - xz 5.2.*  # [not win]
    run:
        - icu 56.*  # [not win]
        - libiconv
        - zlib 1.2.*
        - xz 5.2.*  # [not win]

test:
    requires:
        - python {{ environ['PY_VER'] + '*' }}  # [win]
    files:
        - test.xml
    commands:
        - xmllint test.xml
        - conda inspect linkages -n _test libxml2  # [linux]

about:
    home: http://xmlsoft.org/
    license: MIT
    summary: The XML C parser and toolkit of Gnome

extra:
    recipe-maintainers:
        - ocefpaf
        - jakirkham
        - gillins
